# -*- coding: utf-8 -*-
"""midtermProject

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mQuE67EsDpkkGJVVAV6zAdECFYdc_CuR

**MIDTERM PROJECT CODE**

COSC 5360 (SPRING 2026)

Dr. Massaoudi

TEAM: Hannah Fee and Jareen Mahmood
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, ConfusionMatrixDisplay
from sklearn.datasets import make_classification

# Load Training Data
trainData= pd.read_csv('1990songs_trained_dataset.csv')
print("Shape of the data: ", trainData.shape)
print("Dtypes & Null Values: \n", trainData.info())
print("Class Balance: \n", trainData['Popularity'].value_counts(normalize=True))

# Load Test Data
testData= pd.read_csv('2020song_test_dataset.csv')
print("\nShape of the data: ", testData.shape)
print("Dtypes & Null Values: \n", testData.info())

# Exploratory Data Analysis (EDA)
numeric_cols = ['Tempo', 'Loudness', 'Danceability', 'Energy', 'Rank']
fig, axes= plt.subplots(1, len(numeric_cols), figsize=(20,10))
for i, col in zip(axes, numeric_cols):
    trainData.groupby('Popularity')[col].plot(kind='kde', ax=i, legend=True, title=col)
plt.tight_layout()
#plt.show()

sns.heatmap(trainData[numeric_cols + ['Popularity']].corr(), annot=True, cmap='coolwarm', center=0)
plt.title('Correlation Matrix')
plt.tight_layout()
#plt.show()

# Popularity by genre, tempo, loudness, danceability, energy, rank
print("Popularity by Genre: \n", trainData.groupby('Genre')['Popularity'].mean())
trainData.groupby('Genre')['Popularity'].value_counts(normalize=True).unstack().plot(kind='bar', stacked=False, title='Popularity by Genre')
#plt.show()

print("Popularity by Tempo: \n", trainData.groupby('Tempo')['Popularity'].mean())
trainData.groupby('Tempo')['Popularity'].value_counts(normalize=True).unstack().plot(kind='bar', stacked=False, title='Popularity by Tempo')
#plt.show()

print("Popularity by Loudness: \n", trainData.groupby('Loudness')['Popularity'].mean())
trainData.groupby('Loudness')['Popularity'].value_counts(normalize=True).unstack().plot(kind='bar', stacked=False, title='Popularity by Loudness')
#plt.show()

print("Popularity by Danceability: \n", trainData.groupby('Danceability')['Popularity'].mean())
trainData.groupby('Danceability')['Popularity'].value_counts(normalize=True).unstack().plot(kind='bar', stacked=False, title='Popularity by Danceability')
#plt.show()

print("Popularity by Energy: \n", trainData.groupby('Energy')['Popularity'].mean())
trainData.groupby('Energy')['Popularity'].value_counts(normalize=True).unstack().plot(kind='bar', stacked=False, title='Popularity by Energy')
#plt.show()

print("Popularity by Rank: \n", trainData.groupby('Rank')['Popularity'].mean())
trainData.groupby('Rank')['Popularity'].value_counts(normalize=True).unstack().plot(kind='bar', stacked=False, title='Popularity by Rank')
#plt.show()

# Setup Train/Test Split
important_features = ['Tempo', 'Danceability', 'Energy', 'Rank']
x = trainData[important_features]
y = trainData['Popularity']
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size=0.2, random_state=42)
print("Train Size: ", len(xTrain), "Test Size: ", len(xTest))
print("Train Approved Rate: ", yTrain.mean(), "Test Approved Rate: ", yTest.mean())

# Classification Models
models={
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'Support Vector Machine': SVC(kernel='rbf', random_state=42)
}

for name, model in models.items():
    scores= cross_val_score(model, xTrain, yTrain, cv=5, scoring='accuracy')
    print(f'{name} CV Accuracy: {scores.mean():.4f} (+/- {scores.std():.4f})')

lr= LogisticRegression(max_iter=1000)
lr.fit(xTrain, yTrain)
lrPred= lr.predict(xTest)

rf= RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(xTrain, yTrain)
rfPred= rf.predict(xTest)

svm= SVC(kernel='rbf', random_state=42)
svm.fit(xTrain, yTrain)
svmPred= svm.predict(xTest)

# Performance Evaluation
print("\n\nModel Comparison:")
print(" Logistic Regression Accuracy: ", accuracy_score(yTest, lrPred))
print(" Random Forest Accuracy: ", accuracy_score(yTest, rfPred))
print(" Support Vector Machine Accuracy: ", accuracy_score(yTest, svmPred))

print("\nClassification Report:")
print(" Logistic Regression:\n", classification_report(yTest, lrPred))
print(" Random Forest:\n", classification_report(yTest, rfPred))
print(" Support Vector Machine:\n", classification_report(yTest, svmPred))

print("\nConfusion Matrix:")
print(" Logistic Regression:\n", confusion_matrix(yTest, lrPred))
print(" Random Forest:\n", confusion_matrix(yTest, rfPred))
print(" Support Vector Machine:\n", confusion_matrix(yTest, svmPred))

#Predict on Test Data
xTestFinal= testData[important_features]

testPred= lr.predict(xTestFinal)
lrPredFinal= pd.DataFrame({'Title': testData['Title'], 'Artist': testData['Artist'], 'Predicted Popularity': testPred})
lrPredFinal.to_csv('lr_predictions.csv', index=False)
print("\nLogistic Regression Predictions:\n", lrPredFinal)

testPred= rf.predict(xTestFinal)
rfPredFinal= pd.DataFrame({'Title': testData['Title'], 'Artist': testData['Artist'], 'Predicted Popularity': testPred})
rfPredFinal.to_csv('rf_predictions.csv', index=False)
print("\nRandom Forest Predictions:\n", rfPredFinal)

testPred= svm.predict(xTestFinal)
svmPredFinal= pd.DataFrame({'Title': testData['Title'], 'Artist': testData['Artist'], 'Predicted Popularity': testPred})
svmPredFinal.to_csv('svm_predictions.csv', index=False)
print("\nSVM Predictions:\n", svmPredFinal)

# Load 2020 Songs Train Data
trainData2020= pd.read_csv('2020song_trained_dataset.csv')
print("\nShape of the data: ", trainData2020.shape)
print("Dtypes & Null Values: \n", trainData2020.info())
print("Class Balance: \n", trainData2020['Popularity'].value_counts(normalize=True))

# Load 2020 Songs Test Data
testData2020= pd.read_csv('2020song_test_dataset.csv')
print("\nShape of the data: ", testData2020.shape)
print("Dtypes & Null Values: \n", testData2020.info())

# Exploratory Data Analysis (EDA)
numeric_cols = ['Tempo', 'Loudness', 'Danceability', 'Energy', 'Rank']
fig, axes= plt.subplots(1, len(numeric_cols), figsize=(20,10))
for i, col in zip(axes, numeric_cols):
    trainData2020.groupby('Popularity')[col].plot(kind='kde', ax=i, legend=True, title=col)
plt.tight_layout()
#plt.show()

sns.heatmap(trainData2020[numeric_cols + ['Popularity']].corr(), annot=True, cmap='coolwarm', center=0)
plt.title('Correlation Matrix')
plt.tight_layout()
#plt.show()

# Popularity by genre, tempo, loudness, danceability, energy, rank
print("Popularity by Genre: \n", trainData2020.groupby('Genre')['Popularity'].mean())
trainData2020.groupby('Genre')['Popularity'].value_counts(normalize=True).unstack().plot(kind='bar', stacked=False, title='Popularity by Genre')
#plt.show()

print("Popularity by Tempo: \n", trainData2020.groupby('Tempo')['Popularity'].mean())
trainData2020.groupby('Tempo')['Popularity'].value_counts(normalize=True).unstack().plot(kind='bar', stacked=False, title='Popularity by Tempo')
#plt.show()

print("Popularity by Loudness: \n", trainData2020.groupby('Loudness')['Popularity'].mean())
trainData2020.groupby('Loudness')['Popularity'].value_counts(normalize=True).unstack().plot(kind='bar', stacked=False, title='Popularity by Loudness')
#plt.show()

print("Popularity by Danceability: \n", trainData2020.groupby('Danceability')['Popularity'].mean())
trainData2020.groupby('Danceability')['Popularity'].value_counts(normalize=True).unstack().plot(kind='bar', stacked=False, title='Popularity by Danceability')
#plt.show()

print("Popularity by Energy: \n", trainData2020.groupby('Energy')['Popularity'].mean())
trainData2020.groupby('Energy')['Popularity'].value_counts(normalize=True).unstack().plot(kind='bar', stacked=False, title='Popularity by Energy')
#plt.show()

print("Popularity by Rank: \n", trainData2020.groupby('Rank')['Popularity'].mean())
trainData2020.groupby('Rank')['Popularity'].value_counts(normalize=True).unstack().plot(kind='bar', stacked=False, title='Popularity by Rank')
#plt.show()

# Setup Train/Test Split for 2020 songs
important_features = ['Tempo', 'Danceability', 'Energy', 'Rank']
x = trainData2020[important_features]
y = trainData2020['Popularity']
xTrain2, xTest2, yTrain2, yTest2 = train_test_split(x, y, test_size=0.2, random_state=42)
print("Train Size: ", len(xTrain2), "Test Size: ", len(xTest2))
print("Train Approved Rate: ", yTrain2.mean(), "Test Approved Rate: ", yTest2.mean())

# Classification Models for 2020songs
models2={
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'Support Vector Machine': SVC(kernel='rbf', random_state=42)
}

for name, model in models.items():
    scores2= cross_val_score(model, xTrain2, yTrain2, cv=5, scoring='accuracy')
    print(f'{name} CV Accuracy: {scores2.mean():.4f} (+/- {scores2.std():.4f})')

lr= LogisticRegression(max_iter=1000)
lr.fit(xTrain2, yTrain2)
lrPred2= lr.predict(xTest2)

rf= RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(xTrain2, yTrain2)
rfPred2= rf.predict(xTest2)

svm= SVC(kernel='rbf', random_state=42)
svm.fit(xTrain2, yTrain2)
svmPred2= svm.predict(xTest2)

# Performance Evaluation
print("\n\nModel Comparison:")
print("Logistic Regression Accuracy: ", accuracy_score(yTest2, lrPred2))
print("Random Forest Accuracy: ", accuracy_score(yTest2, rfPred2))
print("Support Vector Machine Accuracy: ", accuracy_score(yTest2, svmPred2))

print("\n\Classification Report:")
print("Logistic Regression:\n", classification_report(yTest2, lrPred2))
print("Random Forest:\n", classification_report(yTest2, rfPred2))
print("Support Vector Machine:\n", classification_report(yTest2, svmPred2))

print("\nConfusion Matrix:")
print("Logistic Regression:\n", confusion_matrix(yTest2, lrPred2))
print("Random Forest:\n", confusion_matrix(yTest2, rfPred2))
print("Support Vector Machine:\n", confusion_matrix(yTest2, svmPred2))

#2nd Predict on Test Data with 2020 songs data only
x2020TestFinal= testData2020[important_features]

testPred2= lr.predict(x2020TestFinal)
lrPredFinal2= pd.DataFrame({'Title': testData2020['Title'], 'Artist': testData2020['Artist'], 'Predicted Popularity': testPred2})
lrPredFinal2.to_csv('lr_predictions2.csv', index=False)
print("\nLogistic Regression Predictions:\n", lrPredFinal2)

testPred2= rf.predict(x2020TestFinal)
rfPredFinal2= pd.DataFrame({'Title': testData2020['Title'], 'Artist': testData2020['Artist'], 'Predicted Popularity': testPred2})
rfPredFinal2.to_csv('rf_predictions2.csv', index=False)
print("\nRandom Forest Predictions:\n", rfPredFinal2)

testPred2= svm.predict(x2020TestFinal)
svmPredFinal2= pd.DataFrame({'Title': testData2020['Title'], 'Artist': testData2020['Artist'], 'Predicted Popularity': testPred2})
svmPredFinal2.to_csv('svm_predictions2.csv', index=False)
print("\nSVM Predictions:\n", svmPredFinal2)

#Comparing accuracy scores of 1990s train data vs. 2020s test data, and 2020 train data vs. 2020 test data
accuracyscoresOne = pd.DataFrame({
    'Model': ['Logistic Regression', 'Random Forest', 'Support Vector Machine'],
    'Accuracy Score': [accuracy_score(yTest, lrPred), accuracy_score(yTest, rfPred), accuracy_score(yTest, svmPred)]})

print(accuracyscoresOne)

accuracyscoresTwo = pd.DataFrame({
    'Model': ['Logistic Regression', 'Random Forest', 'Support Vector Machine'],
    'Accuracy Score': [accuracy_score(yTest2, lrPred2), accuracy_score(yTest2, rfPred2), accuracy_score(yTest2, svmPred2)]})
print (accuracyscoresTwo)

accuracyscoresOne.compare(accuracyscoresTwo)
accuracyscoresOne != accuracyscoresTwo

compareaccuracyscores = pd.merge(accuracyscoresOne, accuracyscoresTwo, on='Model')
print (compareaccuracyscores)

fig, axes = plt.subplots(1, 3, figsize=(15, 5))
plt.suptitle('Comparison of Accuracy Scores')
for i, model_name in enumerate(['Logistic Regression', 'Random Forest', 'Support Vector Machine']):
      plt.subplot(1, 3, i + 1)
      # Extract the accuracy score for the current model from each DataFrame
      accuracy_a = accuracyscoresOne.loc[accuracyscoresOne['Model'] == model_name, 'Accuracy Score'].iloc[0]
      accuracy_b = accuracyscoresTwo.loc[accuracyscoresTwo['Model'] == model_name, 'Accuracy Score'].iloc[0]
      plt.bar(['Dataset A', 'Dataset B'],[accuracy_a, accuracy_b])
      plt.title(f'Accuracy Score - {model_name}')
      plt.ylim(0, 1)
      plt.tight_layout()
plt.show()

# Comparing classification report
datasets = {'Dataset_A': (xTest, yTest), 'Dataset_B': (xTest2, yTest2)}
models_preds = {'Logistic Regression': (lrPred, lrPred2), 'Random Forest': (rfPred, rfPred2), 'SVM': (svmPred, svmPred2)}

# Function to get classification report as a dictionary
def get_classification_report_dict(y_true, y_pred):
    return classification_report(y_true, y_pred, output_dict=True)

# --- Process for Dataset A (1990s songs) ---
reports_A = []
for m_name, (pred_for_A, _) in models_preds.items():
    report_dict = get_classification_report_dict(yTest, pred_for_A)
    # Extract macro avg for comparison
    macro_avg = report_dict['macro avg']
    reports_A.append({
        'Model': m_name,
        'Precision_A': macro_avg['precision'],
        'Recall_A': macro_avg['recall'],
        'F1-Score_A': macro_avg['f1-score'],
        'Support_A': macro_avg['support']
    })
df_report_A = pd.DataFrame(reports_A)

# --- Process for Dataset B (2020s songs) ---
reports_B = []
for m_name, (_, pred_for_B) in models_preds.items():
    report_dict = get_classification_report_dict(yTest2, pred_for_B)
    macro_avg = report_dict['macro avg']
    reports_B.append({
        'Model': m_name,
        'Precision_B': macro_avg['precision'],
        'Recall_B': macro_avg['recall'],
        'F1-Score_B': macro_avg['f1-score'],
        'Support_B': macro_avg['support']
    })
df_report_B = pd.DataFrame(reports_B)

# Merge the two dataframes for comparison
comparison_classification_report = pd.merge(df_report_A, df_report_B, on='Model', how='inner')

print("\nComparison of Macro Average Classification Report Metrics:")
print(comparison_classification_report)

fig, axes = plt.subplots(1, 3, figsize=(15, 5))
plt.suptitle('Comparison of Macro Average Classification Report Metrics')
for i, model_name in enumerate(['Logistic Regression', 'Random Forest', 'SVM']):
    precision_a_value = comparison_classification_report.loc[comparison_classification_report['Model'] == model_name, 'Precision_A'].iloc[0]
    precision_b_value = comparison_classification_report.loc[comparison_classification_report['Model'] == model_name, 'Precision_B'].iloc[0]
    axes[i].bar(['Dataset A', 'Dataset B'], [precision_a_value, precision_b_value])
    axes[i].set_title(f'Precision - {model_name}')
    axes[i].set_ylim(0, 1)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

#comparing confusion metrix
confusion_matrix_A = confusion_matrix(yTest, lrPred)
confusion_matrix_B = confusion_matrix(yTest2, lrPred2)
confusion_matrix_C = confusion_matrix(yTest, rfPred)
confusion_matrix_D = confusion_matrix(yTest2, rfPred2)
confusion_matrix_E = confusion_matrix(yTest, svmPred)
confusion_matrix_F = confusion_matrix(yTest2, svmPred2)

fig, axes = plt.subplots(1, 6, figsize=(27, 5))
plt.suptitle('Comparison of Confusion Matrices')

# Plot Confusion Matrix for Dataset A
disp_A = ConfusionMatrixDisplay(confusion_matrix=confusion_matrix_A)
disp_A.plot(cmap='Reds', ax=axes[0])
axes[0].set_title('Confusion Matrix - Dataset A (Linear Regression) (1990s)')

# Plot Confusion Matrix for Dataset B
disp_B = ConfusionMatrixDisplay(confusion_matrix=confusion_matrix_B)
disp_B.plot(cmap='Greens', ax=axes[1])
axes[1].set_title('Confusion Matrix - Dataset B (Linear Regression) (2020s)')

# Plot Confusion Matrix for Dataset C
disp_C = ConfusionMatrixDisplay(confusion_matrix=confusion_matrix_C)
disp_C.plot(cmap='Reds', ax=axes[2])
axes[2].set_title('Confusion Matrix - Dataset C (Random Forest) (1990s)')

# Plot Confusion Matrix for Dataset D
disp_D = ConfusionMatrixDisplay(confusion_matrix=confusion_matrix_D)
disp_D.plot(cmap='Greens', ax=axes[3])
axes[3].set_title('Confusion Matrix - Dataset D (Random Forest) (2020s)')

# Plot Confusion Matrix for Dataset C
disp_E = ConfusionMatrixDisplay(confusion_matrix=confusion_matrix_E)
disp_E.plot(cmap='Reds', ax=axes[4])
axes[4].set_title('Confusion Matrix - Dataset E (SVM) (1990s)')

# Plot Confusion Matrix for Dataset D
disp_F = ConfusionMatrixDisplay(confusion_matrix=confusion_matrix_F)
disp_F.plot(cmap='Greens', ax=axes[5])
axes[5].set_title('Confusion Matrix - Dataset F (SVM) (2020s)')

plt.tight_layout()
plt.show()

